SandVolleyballWebApp/Models/Court.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SandVolleyballWebApp.Models
{
    public class Court
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string? Description { get; set; }
        public string? Image { get; set; }
        public Address Address { get; set; }
        [ForeignKey("AppUser")]
        public string? AppUserId { get; set; }
        public AppUser? AppUser { get; set; }
    }
}

SandVolleyballWebApp/Controllers/CourtController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SandVolleyballWebApp.Data;
using SandVolleyballWebApp.Interfaces;
using SandVolleyballWebApp.Models;
using SandVolleyballWebApp.Repository;
using SandVolleyballWebApp.Services;
using SandVolleyballWebApp.ViewModels;

namespace SandVolleyballWebApp.Controllers
{
    public class CourtController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IHttpContextAccessor _httpContextAccessor;
        

        public CourtController(IUnitOfWork unitOfWork, IHttpContextAccessor httpContextAccessor)
        {
            _unitOfWork = unitOfWork;
            _httpContextAccessor = httpContextAccessor;
            
        }
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var courts = await _unitOfWork.Court.GetAll();
            return View(courts);
        }
        [Authorize]
        public async Task<IActionResult> Search(string state)
		{
			var courts = await _unitOfWork.Court.GetCourtByState(state);
			return View(courts);
		}
        [Authorize]
		public async Task<IActionResult> Detail(int id)
        {
            Court court = await _unitOfWork.Court.GetByIdAsync(id);
            return View(court);
        }
        [Authorize]
        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            var createVeiwModel = new CreateCourtViewModel { AppUserId = curUserId };
            return View(createVeiwModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCourtViewModel courtVM)
        {
            if (ModelState.IsValid)
            {
                var result = await _unitOfWork.Photo.AddPhotoAsync(courtVM.Image);

                var court = new Court
                {
                    Title = courtVM.Title,
                    Description = courtVM.Description,
                    Image = result.Url.ToString(),
                    AppUserId = courtVM.AppUserId,
                    Address = new Address
                    {
                        Street = courtVM.Address.Street,
                        City = courtVM.Address.City,
                        State = courtVM.Address.State,
                    }
                };
                _unitOfWork.Court.Add(court);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Photo upload failed");
            }

            return View(courtVM);
        }
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var court = await _unitOfWork.Court.GetByIdAsync(id);
            if (court == null) return View("Error");
            var courtVM = new EditCourtViewModel
            {
                Title = court.Title,
                Description = court.Description,
                AddressId = court.Address.Id,
                Address = court.Address,
                URL = court.Image

            };
            return View(courtVM);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditCourtViewModel courtVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit club");
                return View("Edit", courtVM);
            }
            var userCourt = await _unitOfWork.Court.GetByIdAsyncNoTracking(id);

            if (userCourt != null)
            {
                try
                {
                    await _unitOfWork.Photo.DeletePhotoAsync(userCourt.Image);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(courtVM);
                }
                var photoResult = await _unitOfWork.Photo.AddPhotoAsync(courtVM.Image);

                var court = new Court
                {
                    Id = id,
                    Title = courtVM.Title,
                    Description = courtVM.Description,
                    Image = photoResult.Url.ToString(),
                    Address = courtVM.Address
                };
                _unitOfWork.Court.Update(court);
                return RedirectToAction("Index");
            }
            else
            {
                return View(courtVM);
            }
        }
       
        public async Task<IActionResult> Delete(int id)
        {
            var courtDetails = await _unitOfWork.Court.GetByIdAsync(id);
            if (courtDetails == null) return View("Error");
            return View(courtDetails);
        }
      
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteCourt(int id)
        {
            var courtDetails = await _unitOfWork.Court.GetByIdAsync(id);
            if (courtDetails == null) return View("Error");

            _unitOfWork.Court.Delete(courtDetails);
            return RedirectToAction("Index");
        }

    }

}

SandVolleyballWebApp/Controllers/DashboardController.cs
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SandVolleyballWebApp.Data;
using SandVolleyballWebApp.Interfaces;
using SandVolleyballWebApp.Models;
using SandVolleyballWebApp.ViewModels;

namespace SandVolleyballWebApp.Controllers
{
    public class DashboardController : Controller
    { 
        private readonly IUnitOfWork _unitOfWork;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public DashboardController(IUnitOfWork unitOfWork, IHttpContextAccessor httpContextAccessor)
        {
            _unitOfWork = unitOfWork;
            _httpContextAccessor = httpContextAccessor;
        }

        private void MapUserEdit(AppUser user, EditUserDashboardViewModel editVM, ImageUploadResult photoResult)
        {
            user.Id = editVM.Id;
            user.ProfileImageUrl = photoResult.Url.ToString();
            user.Bio = editVM.Bio;
            user.City = editVM.City;
            user.State = editVM.State;
            user.PlayStyleGroup = editVM.PlayStyleGroup;

        }
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var userCourts = await _unitOfWork.Dashboard.GetAllUserCourts();
            var dashboardViewModel = new DashboardViewModel()
            {
                Courts = userCourts
            };
            return View(dashboardViewModel);
        }

        [Authorize]
        public async Task<IActionResult> EditUserProfile()
        {
            var curUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            var user = await _unitOfWork.Dashboard.GetUserById(curUserId);
            if (user == null) return View("Error");
            var editUserViewModel = new EditUserDashboardViewModel()
            {
                Id = curUserId,
                ProfileImageUrl = user.ProfileImageUrl,
                Bio = user.Bio,
                City = user.City,
                State = user.State,
                PlayStyleGroup = user.PlayStyleGroup
            };
            return View(editUserViewModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUserProfilePost(EditUserDashboardViewModel editVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit profile");
                return View("EditUserProfile", editVM);
            }

            var user = await _unitOfWork.Dashboard.GetByIdNoTracking(editVM.Id);

            if (user.ProfileImageUrl == "" || user.ProfileImageUrl == null)
            {
                var photoResult = await _unitOfWork.Photo.AddPhotoAsync(editVM.Image);

                MapUserEdit(user, editVM, photoResult);

                _unitOfWork.Dashboard.Update(user);
                return RedirectToAction("Index");
            }
            else
            {
                try
                {
                    await _unitOfWork.Photo.DeletePhotoAsync(user.ProfileImageUrl);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(editVM);
                }
                var photoResult = await _unitOfWork.Photo.AddPhotoAsync(editVM.Image);

                MapUserEdit(user, editVM, photoResult);

                _unitOfWork.Dashboard.Update(user);

                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AdminEditUser(string id)
        {
            var user = await _unitOfWork.Dashboard.GetUserById(id);
            if (user == null) return View("Error");
            var editUserViewModel = new EditUserDashboardViewModel()
            {
                Id = id,
                ProfileImageUrl = user.ProfileImageUrl,
                Bio = user.Bio,
                City = user.City,
                State = user.State,
                PlayStyleGroup = user.PlayStyleGroup,
            };
            return View(editUserViewModel);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AdminEditUserPost(string id, EditUserDashboardViewModel editVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit profile");
                return View("AdminEditUser", editVM);
            }

            var user = await _unitOfWork.Dashboard.GetByIdNoTracking(id);

            if (user.ProfileImageUrl == "" || user.ProfileImageUrl == null)
            {
                var photoResult = await _unitOfWork.Photo.AddPhotoAsync(editVM.Image);

                MapUserEdit(user, editVM, photoResult);

                _unitOfWork.Dashboard.Update(user);
                return RedirectToAction("Index");
            }
            else
            {
                try
                {
                    await _unitOfWork.Photo.DeletePhotoAsync(user.ProfileImageUrl);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(editVM);
                }
                var photoResult = await _unitOfWork.Photo.AddPhotoAsync(editVM.Image);

                MapUserEdit(user, editVM, photoResult);

                _unitOfWork.Dashboard.Update(user);

                return RedirectToAction("Index", "User");
            }
        }

    }
}

SandVolleyballWebApp/Views/Court/Create.cshtml
@using SandVolleyballWebApp.ViewModels
@model CreateCourtViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<form method="post" asp-action="Create" enctype="Multipart/form-data">
    <input type="hidden" id="AppUserId" name="AppUserId" asp-for="AppUserId" />
  <div class="form-group">
    <label asp-for="Title">Title</label>
    <input asp-for="Title" class="form-control" placeholder="Title">
    <span asp-validation-for="Title" class="text-danger"></span>
  </div>
  <div class="form-group">
    <label asp-for="Description">Description</label>
    <input asp-for="Description" class="form-control" placeholder="Description">
    <span asp-validation-for="Description" class="text-danger"></span>
  </div>
  <div class="form-group">
    <label asp-for="Address.Street">Street</label>
    <input asp-for="Address.Street" class="form-control" placeholder="Street">
    <span asp-validation-for="Address.Street" class="text-danger"></span>
  </div>
  <div class="form-group">
    <label asp-for="Address.City">City</label>
    <input asp-for="Address.City" class="form-control" placeholder="City">
    <span asp-validation-for="Address.City" class="text-danger"></span>
  </div>
  <div class="form-group">
    <label asp-for="Address.State">State</label>
    <input asp-for="Address.State" class="form-control" placeholder="State">
    <span asp-validation-for="Address.State" class="text-danger"></span>
  </div>
   <div class="form-group">
    <label asp-for="Image">Image</label>
    <input asp-for="Image" type="file" class="form-control" placeholder="Image">
    <span asp-validation-for="Image" class="text-danger"></span>
  </div>
  <div>
  <button type="submit" class="btn btn-primary">Submit</button>
        <a asp-controller="Dashboard" asp-action="Index" type="button" class="btn btn-primary">Cancel</a>
    </div>
</form>

SandVolleyballWebApp/Views/Court/Delete.cshtml
@model Court

<h1>Are you sure you want to delete this Court?</h1>

<form method="post" asp-action="Delete" enctype="multipart/form-data">
    <input type="hidden" value="AddressId" id="AddressId" />
    <div class="form-group">
        <label asp-for="Title">Title</label>
        <input asp-for="Title" class="form-control" placeholder="Title">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" class="form-control" placeholder="Description">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.Street">Street</label>
        <input asp-for="Address.Street" class="form-control" placeholder="Street">
        <span asp-validation-for="Address.Street" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.City">City</label>
        <input asp-for="Address.City" class="form-control" placeholder="City">
        <span asp-validation-for="Address.Street" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.State">State</label>
        <input asp-for="Address.State" class="form-control" placeholder="Street">
        <span asp-validation-for="Address.State" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image">Image</label>
        <input asp-for="Image" type="file" class="form-control" placeholder="Image">
        <span asp-validation-for="Image" class="text-danger"></span>

    </div>
    </form>
    <div class="form-group">
        <form action="Delete" method="post">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Confirm" class="btn btn-danger float-right mt-3" />
            <a asp-controller="Dashboard" asp-action="Index" type="button" class="btn btn-danger float-right mt-3">Cancel</a>
        </form>
     </div>

SandVolleyballWebApp/Views/Court/Detail.cshtml
@model Court

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!-- Page Content -->
<div class="container">

	<!-- Portfolio Item Heading -->
	<h1 class="my-4">
		@Model.Title
		<small></small>
	</h1>

	<!-- Portfolio Item Row -->
	<div class="row">

		<div class="col-md-8">
			<img class="img-fluid" src="@Model.Image" alt="">
		</div>

		<div class="col-md-4">
			<h3 class="my-3">Location</h3>
			<ul>
				<li>@($"{@Model.Address.Street}, {@Model.Address.City}, {@Model.Address.State}");</li>
			</ul>
			<h3 class="my-3">Description</h3>
			<p>@Model.Description</p>
		</div>

	</div>
	<!-- /.row -->
	<!-- Related Projects Row -->
	<!-- /.row -->

</div>

SandVolleyballWebApp/Views/Court/Edit.cshtml
@using SandVolleyballWebApp.ViewModels
@model EditCourtViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post" asp-action="Edit" enctype="Multipart/form-data">
	<input type="hidden" value="AddressId" id="AddressId" />
	<div class="form-group">
		<label asp-for="Title">Title</label>
		<input asp-for="Title" class="form-control" placeholder="Title">
		<span asp-validation-for="Title" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Description">Description</label>
		<input asp-for="Description" class="form-control" placeholder="Description">
		<span asp-validation-for="Description" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Address.Street">Street</label>
		<input asp-for="Address.Street" class="form-control" placeholder="Street">
		<span asp-validation-for="Address.Street" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Address.City">City</label>
		<input asp-for="Address.City" class="form-control" placeholder="City">
		<span asp-validation-for="Address.City" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Address.State">State</label>
		<input asp-for="Address.State" class="form-control" placeholder="State">
		<span asp-validation-for="Address.State" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Image">Image</label>
		<input asp-for="Image" type="file" class="form-control" placeholder="Image">
		<span asp-validation-for="Image" class="text-danger"></span>
	</div>
	<button type="submit" class="btn btn-primary">Submit</button>
	<a asp-controller="Court" asp-action="Index" type="button" class="btn btn-primary">Cancel</a>
</form>

SandVolleyballWebApp/Views/Court/Index.cshtml
@model IEnumerable<Court>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form id="seachform" method="post">
	<div style="padding-left:33px" class="row" id="seachbox">
		<div class="col-md-2"> <input placeholder="Search State" class="form-control" type="text" id="state" name="state" /></div>
		<div class="col-md-2"> <input asp-controller="court" asp-action="search" class="btn btn-primary" type="submit" value="search" id="submitsearch" /></div>
	</div>
</form>



<section class="bs-gray-dark d-flex justify-content-center align-items-center h-50 min-vh-50">
	<div class="container">
		<div class="row gy-2">
			@foreach (var item in Model)
			{	
				<div class=" col-lg-3 col-md-4">
					<div class="box bs-gray-dark h-100 d-flex p-4 flex-column text-white">
						<img src="@item.Image" alt="Court Picture" />
						<h6 class="mt-3 h-25" >@item.Title</h6>
						<div class="btn-group mt-auto">
						            <a asp-controller="Court" asp-action="Detail" asp-route-id="@item.Id" type="button" class=" mt-auto btn btn-sm btn-outline-secondary">View</a>
									@if (User.Identity.IsAuthenticated && User.IsInRole("admin")){

										<a asp-controller="Court" asp-action="Edit" asp-route-id="@item.Id" type="button" class="mt-auto btn btn-sm btn-outline-secondary">Edit</a>
										<a asp-controller="Court" asp-action="Delete" asp-route-id="@item.Id" type="button" class="mt-auto btn btn-sm btn-outline-secondary">Delete</a>

									}	
					    </div>	     
					</div>
				</div>
			}
		</div>
	</div>
</section>






@*
<div class="album py-5 bs-gray-dark">
	<div class="container">
		<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
			@foreach (var item in Model)
			{
				<div class="col-md-3">
					<div class="card mb-4 box-shadow">
						<img class="card-img-top" src="@item.Image" width="100%" height="200" alt="Card image cap">
						<div class="card-body">
							<p class="card-text">@item.Title</p>
							<p class="card-text-Description">@item.Description</p>
							<div class="d-flex justify-content-between align-items-center">
								<div class="btn-group">
									<a asp-controller="Court" asp-action="Detail" asp-route-id="@item.Id" type="button" class="btn btn-sm btn-outline-secondary">View</a>
									@if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
									{
										<a asp-controller="Court" asp-action="Edit" asp-route-id="@item.Id" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
										<a asp-controller="Court" asp-action="Delete" asp-route-id="@item.Id" type="button" class="btn btn-sm btn-outline-secondary">Delete</a>
									}

								</div>
							</div>
						</div>
					</div>
				</div>
			}
		</div>
	</div>
</div>*@

SandVolleyballWebApp/Views/Court/Search.cshtml
@model IEnumerable<Court>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form id="seachform" method="post">
	<div style="padding-left:11px" class="row" id="seachbox">
		<div class="col-md-2"> <input placeholder="Search State" class="form-control" type="text" id="state" name="state" /></div>
		<div class="col-md-2"> <input asp-controller="court" asp-action="search" class="btn btn-primary" type="submit" value="search" id="submitsearch" /></div>
	</div>
</form>


<section class="bs-gray-dark d-flex justify-content-center align-items-center h-50 min-vh-50">
	<div class="container">
		<div class="row gy-2">
			@foreach (var item in Model)
			{	
				<div class=" col-lg-3 col-md-4">
					<div class="box bs-gray-dark h-100 d-flex p-4 flex-column text-white">
						<img src="@item.Image" alt="Court Picture" />
						<h6 class="mt-3 h-25" >@item.Title</h6>
						<div class="btn-group mt-auto">
						            <a asp-controller="Court" asp-action="Detail" asp-route-id="@item.Id" type="button" class=" mt-auto btn btn-sm btn-outline-secondary">View</a>
									@if (User.Identity.IsAuthenticated && User.IsInRole("admin")){

										<a asp-controller="Court" asp-action="Edit" asp-route-id="@item.Id" type="button" class="mt-auto btn btn-sm btn-outline-secondary">Edit</a>
										<a asp-controller="Court" asp-action="Delete" asp-route-id="@item.Id" type="button" class="mt-auto btn btn-sm btn-outline-secondary">Delete</a>

									}	
					    </div>	     
					</div>
				</div>
			}
		</div>
	</div>
</section>